### ISSUE TITLE
deploy-partner-pods.sh should check if partner pod is already created

### ISSUE THREAD

**Issue by ramperher** [test-network-function/cnf-certification-test-partner#40]
In [deploy-partner-pods.sh](https://github.com/test-network-function/cnf-certification-test-partner/blob/main/deploy-partner-pods.sh), while the namespace to be used is only created if it is not present, the partner pod does not have that check.

Having said that, I am experiencing problems with the test-network-function containerized version (v3.0.0), which seems to make use of the scripts placed in this repository to create the namespace and partner pod.

In my case, I created both namespace and partner pod before executing the test-network-function container. When executing deploy-partner-pods.sh within the container, I saw that the namespace was not created again because it already existed, but not the same for the partner pod, which was created again. 

This is the log related to this. In fact, I was in a disconnected environment, so the second creation of partner pod failed because it could not retrieve the image from quay.

``` $ ./run-tnf-container.sh -k /home/dciteam/clusterconfigs-cluster5/kubeconfig -t /var/lib/dci-pipeline/test_network_function/test-network-function -o /var/lib/dci-pipeline/test_network_function/test-network-function -f diagnostic access-control networking lifecycle observability platform-alteration operator
-k /home/dciteam/clusterconfigs-cluster5/kubeconfig
-t /var/lib/dci-pipeline/test_network_function/test-network-function
-o /var/lib/dci-pipeline/test_network_function/test-network-function
-f operator platform-alteration observability lifecycle networking access-control diagnostic 
The $TNF_CONTAINER_CLIENT environment variable is not set; defaulting to use: podman
Mounting 1 kubeconfig volume(s):
-v /home/dciteam/clusterconfigs-cluster5/kubeconfig:/usr/tnf/kubeconfig/config:Z
+ podman run --rm --network host -v /home/dciteam/clusterconfigs-cluster5/kubeconfig:/usr/tnf/kubeconfig/config:Z -v /var/lib/dci-pipeline/test_network_function/test-network-function:/usr/tnf/config:Z -v /var/lib/dci-pipeline/test_network_function/test-network-function:/usr/tnf/claim:Z -e KUBECONFIG=/usr/tnf/kubeconfig/config -e TNF_MINIKUBE_ONLY=false -e TNF_NON_INTRUSIVE_ONLY=True -e TNF_DISABLE_CONFIG_AUTODISCOVER=false -e TNF_PARTNER_NAMESPACE= -e TNF_OC_DEBUG_IMAGE_ID=registry.dfwt5g.lab:5000/openshift-release-dev/ocp-v4.0-art-dev@sha256:0f5ce898fbad3671fecd6f797130f950fb1abdbaf0d8154c22e2b59c74e3a918 -e LOG_LEVEL=debug -e PATH=/usr/bin:/usr/local/oc/bin quay.io/testnetworkfunction/test-network-function:latest ./run-cnf-suites.sh -o /usr/tnf/claim -f operator platform-alteration observability lifecycle networking access-control diagnostic -s
make: Entering directory '/usr/tnf-partner/src'
bash ./deploy-partner-pods.sh
namespace tnf already exists, no reason to recreate
deployment.apps/partner configured
pod/partner-8646fb4668-jdcnc condition met
error: timed out waiting for the condition on pods/partner-68cf756959-6cz96
make: *** [Makefile:8: install-partner-pods] Error 1
make: Leaving directory '/usr/tnf-partner/src'
```

The result is, I had two partner pods running in the tnf namespace. Then, when the suite was about to be executed, it printed the following error: 

```
time="2021-09-23T12:04:48Z" level=fatal msg="failed to identify a single test orchestrator container: expected exactly one container, got 2 for label test-network-function.com/generic=orchestrator"
```

So, in the end, I was not able to execute the suites because there were two partner pods running, and I cannot rely on the one provided by the test-network-function container because we are working on a disconnected environment.

The proposed solution is to add a new check in deploy-partner-pods.sh to avoid recreating the partner pod if it is already present in the namespace (e.g. looking for pods with test-network-function.com/generic=orchestrator label).

**Comment by jun-rh** [comment]
The intent is to allow multiple partner pods as long as they are in different namespaces. The v3.0.0 container image you used is our last released version. To test with the latest, use the image tag option with run-tnf-continer.sh:

`-i quay.io/testnetworkfunction/test-network-function:unstable`

**Comment by jun-rh** [comment]
As to the partner pod image, yes, it would have to be mirrored locally first for disconnected environment. But you need that no matter whether running tnf binary or container, right?

**Comment by ramperher** [comment]
Hi Jun. I understand what you comment, but the issue is not related to that at all. The problem comes with what you are saying, _"the intent is to allow multiple partner pods as long as they are in different namespaces"_. Let me explain my situation with that, because maybe I explained myself wrongly. 

What I mean is, before running run-tnf-container.sh, I have already created a partner pod running in the desired namespace. However, `run-tnf-container.sh` calls `deploy-partner-pods.sh`, and this script creates a new partner pod in the same namespace, without checking if it is already created or not. Of course, it is fine to allow having multiple partner pods in different namespaces, but in this case, I have already one partner pod in one namespace, and the script tries to create a new one in the same namespace. 

Due to this, it is happening two things in my scenario:

- I have two partner pods deployed in the same namespace, and when running the suite, it complains because there are more than one partner pod in the namespace, and it does not execute the tests.
- Moreover, as I am in a disconnected enviornment, I would need to modify the [partner deployment](https://github.com/test-network-function/cnf-certification-test-partner/blob/main/local-test-infra/local-partner-deployment.yaml#L26) used by `deploy-partner-pods.sh` to point to our local registry instead of quay. Of course, when I create the partner pod with our scripts, we take care of doing this modification, so that the pod is created by using the image from the local registry. However, when using the test-network-function container, as `deploy-partner-pods.sh` is executed within the container, there is no way of modifying `local-partner-deployment.yaml` to point to a local registry. So, as a result, the second partner pod never gets the Running status, because it tries to use the quay image and we are in a disconnected environment, so external connections are not possible.

That's why I was saying if `deploy-partner-pods.sh` can include a check to avoid creating again the partner pod if it is already present in the targeted namespace, this would fix this issue.

**Comment by jun-rh** [comment]
I get the second issue now for the container case. We will add a way of overriding the default image repo location. On the first issue, we do limit one partner pod per namespace right now. Maybe the one you have in the tnf namespace was created long time ago when it was still a standalone pod? If the name is just "partner" without the hash suffix, it would be the case. You can simply delete that one. We had changed it to a replica 1 deployment. Now it should be named like: `partner-68cf756959-kr4k7`

**Comment by ramperher** [comment]
In my case, I am using the same partner deployment you have defined [here](https://github.com/test-network-function/cnf-certification-test-partner/blob/main/local-test-infra/local-partner-deployment.yaml). The only difference is that I change the image to be used to point to our local registry, as we are in a disconnected environment.

The thing is, this partner deployment is created before running the containerized test suite. Then, when the suite is run, the partner deployment is created again in a new replicaset. In fact, it should not do it, because there is already a deployment and a replicaset with the "partner" name created, as you said, but it does it in fact. I don't know if, because I am using a different image, the `oc apply` command used to create the partner pod does not see the other partner pod and then creates the second one.

In any case, I think that, by including [this kind of logic that you already used in previous commits](https://github.com/test-network-function/cnf-certification-test-partner/blob/7604d7e4931c92f629a138532eb0109107a0e276/deploy-all.sh#L36-L43), it should also fix this problem. Or also, to check just the running partner pods and discard the ones that are not in running state (because, in my case, it is detecting two partner pods in the same namespace, but one of them is not in running state).

**Comment by ramperher** [comment]
With your last change included in https://github.com/test-network-function/cnf-certification-test-partner/pull/41, after testing the containerized tnf without deploying the partner pod beforehand, I can confirm it works and the partner pod is created correctly, so you can close this issue if you want (or I can do it tomorrow). Thanks for your support!
